"""add updated field ot user

Revision ID: adebfc4691e6
Revises: 3a91cc42d28e
Create Date: 2024-12-22 15:04:02.293687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adebfc4691e6'
down_revision: Union[str, None] = '3a91cc42d28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_set_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_set_time')
    # ### end Alembic commands ###
